export default {
  ignoreDependencies: [
    "virtual:uno.css",
    "eslint-import-resolver-typescript",

    // dev dependency for orval and bun issue `SyntaxError: Unexpected token ':'`,
    // is not used directly but is necessary to avoid the issue.
    "ajv",
  ],
  ignore: [
    // excluded code generated by orval since the exports will be used progressively
    "./src/api/**",

    // excluded config file since it is used by orval to generate code
    "orval.config.ts",
  ],
};
