export default {
  ignoreDependencies: ["virtual:uno.css", "eslint-import-resolver-typescript"],
  ignore: [
    // excluded code generated by orval since the exports will be used progressively
    "./src/api/**",

    // excluded config file since it is used by orval to generate code
    "orval.config.ts",
  ],
};
