/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chained Notes API
 * An application for chained notes.
 * OpenAPI spec version: 1.0.0
 */
export interface PatchedNoteRequest {
  /** @minLength 1 */
  body?: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  title?: string;
}

export interface NoteRequest {
  /** @minLength 1 */
  body: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  title: string;
}

export interface Note {
  body: string;
  readonly id: number;
  /** @maxLength 255 */
  title: string;
}
