/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Chained Notes API
 * An application for chained notes.
 * OpenAPI spec version: 1.0.0
 */
export interface PatchedNoteRequest {
  /** @minLength 1 */
  body?: string;
  /** @minLength 1 */
  title?: string;
}

export interface NoteRequest {
  /** @minLength 1 */
  body: string;
  /** @minLength 1 */
  title: string;
}

export interface Note {
  body: string;
  readonly id: number;
  title: string;
}

export const getApiNotesListUrl = () => {
  return `/api/notes/`;
};

export const apiNotesList = async (options?: RequestInit): Promise<Note[]> => {
  const res = await fetch(getApiNotesListUrl(), {
    ...options,
    method: "GET",
  });

  return res.json();
};

export const getApiNotesCreateUrl = () => {
  return `/api/notes/`;
};

export const apiNotesCreate = async (
  noteRequest: NoteRequest,
  options?: RequestInit,
): Promise<Note> => {
  const res = await fetch(getApiNotesCreateUrl(), {
    ...options,
    method: "POST",
    body: JSON.stringify(noteRequest),
  });

  return res.json();
};

export const getApiNotesRetrieveUrl = (id: number) => {
  return `/api/notes/${id}/`;
};

export const apiNotesRetrieve = async (
  id: number,
  options?: RequestInit,
): Promise<Note> => {
  const res = await fetch(getApiNotesRetrieveUrl(id), {
    ...options,
    method: "GET",
  });

  return res.json();
};

export const getApiNotesUpdateUrl = (id: number) => {
  return `/api/notes/${id}/`;
};

export const apiNotesUpdate = async (
  id: number,
  noteRequest: NoteRequest,
  options?: RequestInit,
): Promise<Note> => {
  const res = await fetch(getApiNotesUpdateUrl(id), {
    ...options,
    method: "PUT",
    body: JSON.stringify(noteRequest),
  });

  return res.json();
};

export const getApiNotesPartialUpdateUrl = (id: number) => {
  return `/api/notes/${id}/`;
};

export const apiNotesPartialUpdate = async (
  id: number,
  patchedNoteRequest: PatchedNoteRequest,
  options?: RequestInit,
): Promise<Note> => {
  const res = await fetch(getApiNotesPartialUpdateUrl(id), {
    ...options,
    method: "PATCH",
    body: JSON.stringify(patchedNoteRequest),
  });

  return res.json();
};

export const getApiNotesDestroyUrl = (id: number) => {
  return `/api/notes/${id}/`;
};

export const apiNotesDestroy = async (
  id: number,
  options?: RequestInit,
): Promise<void> => {
  const res = await fetch(getApiNotesDestroyUrl(id), {
    ...options,
    method: "DELETE",
  });

  return res.json();
};
