/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Chained Notes API
 * An application for chained notes.
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  Note,
  NoteRequest,
  PatchedNoteRequest,
} from "./chainedNotesAPI.schemas";
import { customInstance } from "../orval/custom-axios-instance";
import type { ErrorType, BodyType } from "../orval/custom-axios-instance";

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const apiNotesList = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<Note[]>(
    { url: `/api/notes/`, method: "GET", signal },
    options,
  );
};

export const getApiNotesListQueryKey = () => {
  return [`/api/notes/`] as const;
};

export const getApiNotesListQueryOptions = <
  TData = Awaited<ReturnType<typeof apiNotesList>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof apiNotesList>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getApiNotesListQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof apiNotesList>>> = ({
    signal,
  }) => apiNotesList(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof apiNotesList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ApiNotesListQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiNotesList>>
>;
export type ApiNotesListQueryError = ErrorType<unknown>;

export function useApiNotesList<
  TData = Awaited<ReturnType<typeof apiNotesList>>,
  TError = ErrorType<unknown>,
>(options: {
  query: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof apiNotesList>>, TError, TData>
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof apiNotesList>>,
        TError,
        TData
      >,
      "initialData"
    >;
  request?: SecondParameter<typeof customInstance>;
}): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useApiNotesList<
  TData = Awaited<ReturnType<typeof apiNotesList>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof apiNotesList>>, TError, TData>
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof apiNotesList>>,
        TError,
        TData
      >,
      "initialData"
    >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useApiNotesList<
  TData = Awaited<ReturnType<typeof apiNotesList>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof apiNotesList>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useApiNotesList<
  TData = Awaited<ReturnType<typeof apiNotesList>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof apiNotesList>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getApiNotesListQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const apiNotesCreate = (
  noteRequest: BodyType<NoteRequest>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<Note>(
    {
      url: `/api/notes/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: noteRequest,
    },
    options,
  );
};

export const getApiNotesCreateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiNotesCreate>>,
    TError,
    { data: BodyType<NoteRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiNotesCreate>>,
  TError,
  { data: BodyType<NoteRequest> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiNotesCreate>>,
    { data: BodyType<NoteRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return apiNotesCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApiNotesCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiNotesCreate>>
>;
export type ApiNotesCreateMutationBody = BodyType<NoteRequest>;
export type ApiNotesCreateMutationError = ErrorType<unknown>;

export const useApiNotesCreate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiNotesCreate>>,
    TError,
    { data: BodyType<NoteRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof apiNotesCreate>>,
  TError,
  { data: BodyType<NoteRequest> },
  TContext
> => {
  const mutationOptions = getApiNotesCreateMutationOptions(options);

  return useMutation(mutationOptions);
};

export const apiNotesRetrieve = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<Note>(
    { url: `/api/notes/${id}/`, method: "GET", signal },
    options,
  );
};

export const getApiNotesRetrieveQueryKey = (id: number) => {
  return [`/api/notes/${id}/`] as const;
};

export const getApiNotesRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof apiNotesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiNotesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getApiNotesRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apiNotesRetrieve>>
  > = ({ signal }) => apiNotesRetrieve(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof apiNotesRetrieve>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ApiNotesRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiNotesRetrieve>>
>;
export type ApiNotesRetrieveQueryError = ErrorType<unknown>;

export function useApiNotesRetrieve<
  TData = Awaited<ReturnType<typeof apiNotesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiNotesRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiNotesRetrieve>>,
          TError,
          TData
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useApiNotesRetrieve<
  TData = Awaited<ReturnType<typeof apiNotesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiNotesRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiNotesRetrieve>>,
          TError,
          TData
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useApiNotesRetrieve<
  TData = Awaited<ReturnType<typeof apiNotesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiNotesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useApiNotesRetrieve<
  TData = Awaited<ReturnType<typeof apiNotesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiNotesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getApiNotesRetrieveQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const apiNotesUpdate = (
  id: number,
  noteRequest: BodyType<NoteRequest>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<Note>(
    {
      url: `/api/notes/${id}/`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: noteRequest,
    },
    options,
  );
};

export const getApiNotesUpdateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiNotesUpdate>>,
    TError,
    { id: number; data: BodyType<NoteRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiNotesUpdate>>,
  TError,
  { id: number; data: BodyType<NoteRequest> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiNotesUpdate>>,
    { id: number; data: BodyType<NoteRequest> }
  > = (props) => {
    const { id, data } = props ?? {};

    return apiNotesUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApiNotesUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiNotesUpdate>>
>;
export type ApiNotesUpdateMutationBody = BodyType<NoteRequest>;
export type ApiNotesUpdateMutationError = ErrorType<unknown>;

export const useApiNotesUpdate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiNotesUpdate>>,
    TError,
    { id: number; data: BodyType<NoteRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof apiNotesUpdate>>,
  TError,
  { id: number; data: BodyType<NoteRequest> },
  TContext
> => {
  const mutationOptions = getApiNotesUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};

export const apiNotesPartialUpdate = (
  id: number,
  patchedNoteRequest: BodyType<PatchedNoteRequest>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<Note>(
    {
      url: `/api/notes/${id}/`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchedNoteRequest,
    },
    options,
  );
};

export const getApiNotesPartialUpdateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiNotesPartialUpdate>>,
    TError,
    { id: number; data: BodyType<PatchedNoteRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiNotesPartialUpdate>>,
  TError,
  { id: number; data: BodyType<PatchedNoteRequest> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiNotesPartialUpdate>>,
    { id: number; data: BodyType<PatchedNoteRequest> }
  > = (props) => {
    const { id, data } = props ?? {};

    return apiNotesPartialUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApiNotesPartialUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiNotesPartialUpdate>>
>;
export type ApiNotesPartialUpdateMutationBody = BodyType<PatchedNoteRequest>;
export type ApiNotesPartialUpdateMutationError = ErrorType<unknown>;

export const useApiNotesPartialUpdate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiNotesPartialUpdate>>,
    TError,
    { id: number; data: BodyType<PatchedNoteRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof apiNotesPartialUpdate>>,
  TError,
  { id: number; data: BodyType<PatchedNoteRequest> },
  TContext
> => {
  const mutationOptions = getApiNotesPartialUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};

export const apiNotesDestroy = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/api/notes/${id}/`, method: "DELETE" },
    options,
  );
};

export const getApiNotesDestroyMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiNotesDestroy>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiNotesDestroy>>,
  TError,
  { id: number },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiNotesDestroy>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return apiNotesDestroy(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApiNotesDestroyMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiNotesDestroy>>
>;

export type ApiNotesDestroyMutationError = ErrorType<unknown>;

export const useApiNotesDestroy = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiNotesDestroy>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof apiNotesDestroy>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getApiNotesDestroyMutationOptions(options);

  return useMutation(mutationOptions);
};
