name: Run Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  playwright:
    name: "Playwright Tests"
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Bun
        run: npm install -g bun

      - name: Install packages
        run: bun install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start the services
        run: docker compose up
        env:
          # TODO: move non-sensitive variables to GitHub variables
          VITE_AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          VITE_AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          VITE_AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}

          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}

          VITE_BACKEND_URL: https://localhost

          PROJECT_NAME: "app"
          PROJECT_DATA_DIR: "./data/db"

          APPLICATION_CONTAINER_NAME: "app"

          # TODO: move non-sensitive constant values to docker compose defaults
          DATABASE_ENGINE: "django.db.backends.postgresql"
          DATABASE_NAME: "app_db"
          DATABASE_USER: "admin"
          DATABASE_PASSWORD: "12345678"
          DATABASE_HOST: "database"
          DATABASE_PORT: 5432
          DATABASE_CONTAINER_NAME: "db"

      - name: Run e2e tests
        run: bun run test:e2e
        env:
          HOME: /root
