name: Lint code

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Bun
        run: npm install -g bun

      - name: Install packages
        run: bun install

      - name: Lint code
        run: bun run lint
